spring.application.name=webhookreceiver
server.port=8081
spring.profiles.active=local

# PostgreSQL Datasource Routing Layer
spring.datasource.url=jdbc:postgresql://localhost:5432/arafi?options=-c%20search_path%3Darafi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Transaction Metrics
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari Connection Optimization Metrics
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Variable Token Injections
arafi.nomba.signing.key=${nomba-signing-key}